### ISSUE TITLE
Readme steps are not elaborated

### ISSUE THREAD

**Issue by sguttikon** [sayands/sgaligner#4]
Hi, could you please elaborate more in detail reproducing steps. Such as for the 'Data Generation' step its not clear currently -
   1) from where 'train_scans.txt' 'validation_scans.txt' files coming from they are not present in 3dssg.zip file
   2) how are 'labels.instances.align.annotated.v2.pkl' generated
   3) where is this 'obj_attr.pkl' file coming from ?

```
======== Scan3R Subscan preprocessing with Scene Graphs using config file : configs/scan3r/scan3r_ground_truth.yaml ========
[INFO] Processing subscans from val split
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 843/843 [02:24<00:00,  5.82it/s]
[INFO] Updating Overlap Data..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1911/1911 [00:00<00:00, 168106.44it/s]
[INFO] Saving val scan ids...
843
[INFO] Starting BOW Feature Calculation For Node Attribute Features...
Traceback (most recent call last):
  File "/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/preprocessing/scan3r/preprocess.py", line 355, in <module>
    calculate_bow_node_attr_feats(data_write_dir)
  File "/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/preprocessing/scan3r/preprocess.py", line 312, in calculate_bow_node_attr_feats
    word_2_ix = common.load_pkl_data(define.OBJ_ATTR_FILENAME)
  File "/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/./utils/common.py", line 14, in load_pkl_data
    with open(filename, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/guttikonda/Documents/SceneGraph/datasets/3RScan/out/files/obj_attr.pkl'

```

**Comment by sayands** [comment]
Hi, please find my answers here :

1 & 2 : These files are available with download of the 3RScan dataset.

3 : The ``obj_attr.pkl`` is available with the provided meta downloads.

Both links are provided in the "Downloads" section of the README - [here](https://github.com/sayands/sgaligner/blob/main/README.md?#downloads-droplet).

**Comment by sguttikon** [comment]
What about align.annotated.v2.ply ?
```
  File "/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/preprocessing/scan3r/generate_subscans.py", line 46, in <module>
    sub_gen_scan3r[idx, False]
  File "/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/./preprocessing/scan3r/subgenscan3r.py", line 174, in __getitem__
    ply_data = scan3r.load_ply_data(self.scene_dir, scan_id, self.label_file_name)
  File "/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/./utils/scan3r.py", line 54, in load_ply_data
    file = open(filename_in, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/guttikonda/Documents/SceneGraph/OriginalWorks/sgaligner/datasets/3RScan/scenes/7272e16c-a01b-20f6-8961-a0927b4a7629/labels.instances.align.annotated.v2.ply'
```

**Comment by sayands** [comment]
You need to use the repo from [here](``https://github.com/ShunChengWu/3DSSG/blob/master/data_processing/transform_ply.py``), updated the README. Thanks for pointing out!
